/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#define LOG_NDEBUG 0
#define LOG_TAG "bluetoothtestmode"

#include <cutils/log.h>

#include <errno.h>
 
#include "masterblaster.h"
#include "btconfig.c"

/* Header for class com_android_engineeringmode_bluetoothtest_BluetoothTestModeUtils */

#ifndef _Included_com_android_engineeringmode_bluetoothtest_BluetoothTestModeUtils
#define _Included_com_android_engineeringmode_bluetoothtest_BluetoothTestModeUtils
#ifdef __cplusplus
extern "C" {
#endif

int hci_enable_device_under_test_mode()
{
	ALOGV("hci_enable_device_under_test_mode in\n");

    int ret = -1;
    int dev_id = -1;

	dev_id = init_smd("/dev/smd3");
    if (dev_id < 0)
    {
		ALOGE("Can not open file /dev/smd3,maybe file is not exist or no permission to access \n");
        return ret;
    }

	ret = hci_send_cmd(dev_id, 0x06, 0x0003, 0, NULL);
	if (ret < 0)
	{
		ALOGE("Enable Device Under Test Mode Command failure");
		fprintf(stderr, "Enable Device Under Test Mode Command failure hci%d: %s (%d)\n",
						dev_id, strerror(errno), errno);
		goto failed;
	}

	char buf0[] = {0x02, 0x00, 0x02};
	ret = hci_send_cmd(dev_id, 0x03, 0x0005, 3, (void *)buf0);
	if (ret < 0)
	{
		ALOGE("Set Event Filter Command failure");
		fprintf(stderr, "Auto Accept All Connections command failure hci%d: %s (%d)\n",
						dev_id, strerror(errno), errno);
		goto failed;
	}

	char buf1 = 0x03;
	ret = hci_send_cmd(dev_id, 0x03, 0x001A, 1, (void *)&buf1);
	if (ret < 0)
	{
		ALOGE("Write Scan Enable Command failure");
		fprintf(stderr, "Write Scan Enable Command failure hci%d: %s (%d)\n",
						dev_id, strerror(errno), errno);
		goto failed;
	}

	char buf2 = 0x00;
	ret = hci_send_cmd(dev_id, 0x03, 0x0020, 1, (void *)&buf2);
	if (ret < 0)
	{
		ALOGE("Write Authentication Enable Command failure");
		fprintf(stderr, " Disable Authentication Command failure hci%d: %s (%d)\n",
						dev_id, strerror(errno), errno);
		goto failed;
	}

	char buf3 = 0x00;
	ret = hci_send_cmd(dev_id, 0x03, 0x0022, 1, (void *)&buf3);
	if (ret < 0)
	{
		ALOGE("Disable Encryption Command failure");
		fprintf(stderr, " Disable Encryption Command failure hci%d: %s (%d)\n",
						dev_id, strerror(errno), errno);
		goto failed;
	}

	goto done;

failed:
    close(dev_id);
	ALOGV("hci_enable_device_under_test_mode Failed\n");
    return ret;

done:
    close(dev_id);
	ALOGV("hci_enable_device_under_test_mode OUT\n");
    return ret;
}

int hci_disable_device_under_test_mode()
{
	int ret = -1;
    int dev_id = -1;

	dev_id = init_smd("/dev/smd3");
    if (dev_id < 0) {
		ALOGE("Can not open file /dev/smd3,maybe file is not exist or no permission to access \n");
        return ret;
    }

	ret = hci_send_cmd(dev_id, 0x03, 0x0003, 0, NULL);
	if (ret < 0)
	{
		ALOGE("Disable Device Under Test Mode Command failure");
		fprintf(stderr, "Disable Device Under Test Mode Command failure hci%d: %s (%d)\n",
						dev_id, strerror(errno), errno);
		goto failed;
	}

	goto done;

failed:
    close(dev_id);
	ALOGE("hci_Disable_device_under_test_mode Failed\n");
    return ret ;

done:
    close(dev_id);
	ALOGV("hci_Disable_device_under_test_mode OUT\n");
    return ret ;
}

/*
 * Class:     com_android_engineeringmode_bluetoothtest_BluetoothTestModeUtils
 * Method:    enterTestModeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL enterTestModeNative
  (JNIEnv *env, jobject obj) {
	return hci_enable_device_under_test_mode();
}

/*
 * Class:     com_android_engineeringmode_bluetoothtest_BluetoothTestModeUtils
 * Method:    quitTestModeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL quitTestModeNative
  (JNIEnv *env, jobject obj) {
	return hci_disable_device_under_test_mode();
}




JNINativeMethod gMethods[] = {
	{ "enterTestModeNative", "()I",  (void*) enterTestModeNative },
    { "quitTestModeNative", "()I",  (void*) quitTestModeNative },
};


int registerNativeMethods(JNIEnv* env, const char* className,
    JNINativeMethod* gMethods, int numMethods)
{
    jclass clazz;

    clazz = (*env)->FindClass(env, className);
    if (clazz == NULL) {
        printf("Native registration unable to find class '%s'\n", className);
        return JNI_FALSE;
    }
    if ((*env)->RegisterNatives(env, clazz, gMethods, numMethods) < 0) {
        printf("RegisterNatives failed for '%s'\n", className);
        return JNI_FALSE;
    }

    return JNI_TRUE;
}

int registerNatives(JNIEnv *env)
{
    const char* const kClassPathName = "com/android/engineeringmode/specialtest/bluetooth/BluetoothTestModeUtils";
    return registerNativeMethods(env,
            kClassPathName, gMethods, sizeof(gMethods) / sizeof(gMethods[0]));
}

/*
 * Returns the JNI version on success, -1 on failure.
 */

jint JNI_OnLoad(JavaVM* vm, void* reserved)
{
    JNIEnv* env = NULL;
    jint result = -1;

    if ((*vm)->GetEnv(vm,(void**) &env, JNI_VERSION_1_4) != JNI_OK) {
	//if ((*vm)->GetEnv((void**)&env, JNI_VERSION_1_4) != JNI_OK) {
		printf("ERROR: GetEnv failed\n");
		goto bail;
	}

    if (!registerNatives(env)) {
        printf("ERROR: BinaryDictionary native registration failed\n");
        goto bail;
    }

    /* success -- return valid version number */
    result = JNI_VERSION_1_4;

bail:
    return result;
}

#ifdef __cplusplus
}
#endif
#endif
